import { Alkatra } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Toaster } from 'react-hot-toast';

const alkatra = Alkatra({
  subsets: ['latin'],
  weight: '400',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={alkatra.className}>
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
